lane :test do
  run_tests_firebase_testlab(
    project_id: "your-firebase-project-id",
    devices: [
      {
        model: "Nexus6P",
        version: "27"
      }
    ],
    delete_firebase_files: true
  )
end
